[debian]
vm-debian12-01 ansible_host=4.221.38.103

[ubuntu]
vm-ubuntu24-01 ansible_host=102.133.176.75
vm-ubuntu24-02 ansible_host=40.123.241.126

[all:vars]
ansible_python_interpreter=/usr/bin/python3